version: "3.9"

services:
  backend:
    build: ./backend
    image: role_fortal_backend:dev
    container_name: artigos_backend
    command: ["python", "site.py"]
    ports:
      - "5001:5001"
    volumes:
      - data:/app/data
    restart: always

  fetcher:
    build: ./backend
    image: role_fortal_backend:dev
    container_name: artigos_fetcher
    command: ["python", "fetch_articles.py"]
    volumes:
      - data:/app/data

  frontend:
    build: ./frontend
    image: role_fortal_frontend:dev
    container_name: artigos_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  data:
